apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imageprocessingclasses.image.cloud.atomix.io
spec:
  group: image.cloud.atomix.io
  names:
    kind: ImageProcessingClass
    listKind: ImageProcessingClassList
    plural: imageprocessingclasses
    singular: imageprocessingclass
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                imagePullPolicy:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 9
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: image-processing-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - cloud.atomix.io
      - image.cloud.atomix.io
    resources:
      - '*'
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-processing-controller
subjects:
  - kind: ServiceAccount
    name: image-processing-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: image-processing-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-processing-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: image-processing-controller
  template:
    metadata:
      labels:
        name: image-processing-controller
    spec:
      serviceAccountName: image-processing-controller
      containers:
        - name: image-processing-controller
          # Replace this with the built image name
          image: image-processing-controller:latest
          command:
            - image-processing-controller
          imagePullPolicy: IfNotPresent

          env:
            - name: CONTROLLER_NAME
              value: "image-processing-controller"
            - name: CONTROLLER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace